### ISSUE TITLE
Incorrectly formatted report when using `--cov-report=term`

### ISSUE THREAD

**Issue by gaursagar21** [MishaKav/pytest-coverage-comment#147]
Hey!
I don't need to see "Missing" column in report. So I am running the action with following command.

`pytest --junitxml=pytest.xml --cov-report=term --cov=app tests/ | tee pytest-coverage.txt`
Ref: https://pytest-cov.readthedocs.io/en/latest/reporting.html

The `term` option removes "Missing" column from report.
<img width="903" alt="Screenshot 2023-11-21 at 16 02 43" src="https://github.com/MishaKav/pytest-coverage-comment/assets/40263793/9fb455fe-b154-4ec0-bad3-c6a9ee5b32bb">

However, the HTML report generated is not formatted correctly when using the `term` option. Data gets incorrectly added in the "Missing" column of the report.
<img width="865" alt="Screenshot 2023-11-21 at 15 57 59" src="https://github.com/MishaKav/pytest-coverage-comment/assets/40263793/ca673088-ea59-4fdf-8be0-e1d10871fdf8">

**Comment by MishaKav** [comment]
You are right, the action will not work properly without `--cov-report=term-missing`, because the **main goal** of this action is to show the `coverage` and to point you to missing lines.

So, I can only suggest you run the report with `--cov-report=term-missing` or don't use the HTML table as a report, because it is against the main idea of this action.
