### ISSUE TITLE
Respect value of `defaults.run.working-directory` for file paths

### ISSUE THREAD

**Issue by michael-pattern** [MishaKav/pytest-coverage-comment#161]
Paths for `pytest-coverage-path` and `junitxml-path` should respect the value of `defaults.run.working-directory` if they are set

**Comment by MishaKav** [comment]
Thank you, I will check this and try to implement it if possible.

**Comment by MishaKav** [comment]
@michael-pattern according to [my code](https://github.com/MishaKav/pytest-coverage-comment/blob/main/src/utils.js#L12) and [github documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#:~:text=the%20workflow%20file.-,GITHUB_WORKSPACE,-The%20default%20working) it's already should support for this.
I have nothing to do with it because the only way to get the default directory is by `GITHUB_WORKSPACE` and I've already done it.
Can you recheck it please and provide some example?

**Comment by MishaKav** [comment]
I will close this issue now, feel free to reopen.
