### ISSUE TITLE
Display number of warnings

### ISSUE THREAD

**Issue by vakker** [MishaKav/pytest-coverage-comment#31]
Hi,
The output of pytest also counts the number of warning, e.g.:
```
...
=================== 34 passed, 3 warnings in 1.25s ==============
```
It could be parsed from `pytest-coverage.txt` and displayed along the pass/error/skip/fail stats.

**Comment by MishaKav** [comment]
It's can't be along the pass/error/skip/fail stats, because it's not a part of JUnit XML format. So it can be very confusing to people.
But I added `number of warnings` to the output params in #32.
You can also see it in the [readme](https://github.com/marketplace/actions/pytest-coverage-comment#output-variables:~:text=warnings)
